---
title: "Programming Assignment 2"
author: "Joseph Walker - jpwalker625@gmail.com"
date: "February 20, 2017"
output: html_document
---
##Problem 1:

Read in the following Mixpanel Web Analytics data sets: 
* berkeley_event-export.json 
* berkeley_people-export.json

```{r read data sets, include=FALSE}
library()
library(dplyr)

events <- fromJSON("berkeley_event-export.json", flatten = TRUE)

people <- fromJSON("berkeley_people-export.json", flatten = TRUE)
```

Join events & people into one data frame, `events_people`
```{r join data sets}

events_people <- full_join(events, people, by = "distinct_id")

```

Tidy the Data

```{r snake_case function, echo=TRUE, message=FALSE, warning=FALSE}

# A function to convert the column names to snake case
fix_column_names <- function(x){
  s <- gsub("properties\\.\\$", "", x) # remove the 'properties(.$)' jargon from beginning of colname
  s <- gsub("\\<properties\\>(.)", "", s) # remove 'properties(.)' jargon from colnames where it is all one word
  s <- gsub("\\.", "_", x) #replace dot (.) with underscore (_)
  s <- gsub("(.)([A-Z][a-z]+)", "\\1_\\2", s) # Separate w/ underscores on capitalization
  s <- tolower(gsub("([a-z0-9])([A-Z])", "\\1_\\2", s)) # lowercase
  s <- gsub("__", "_", s) # double to single underscore
  s <- gsub("^[_, .]", "", s) # del first char underscore "_" or period "."
  s <- gsub(' ', '', s) # remove spaces
}

# Apply the function to the col names in the events_people Data Set
colnames(events_people) <- colnames(events_people) %>% fix_column_names()

# Convert 'NAs' to 'None' in the 'Artist' variable
events_people$artist[is.na(events_people$artist)] <- 'None'

# Convert 'NAs to 'No Page Name' in the 'Page_Name' variable
events_people$page_name[is.na(events_people$page_name)] <- "No Page Name"
```

Plot using `GGPLOT2`

```{r Bar Plot}
library(ggplot2)

p <- ggplot(events_people, aes(x = page_name, fill = artist)) +
  geom_bar()
p
```

##Problem 2:

Read in the AOL Search Data
```{r AOL Data Set}
library(readr)
aol_data <- read_tsv("user-ct-test-collection-01.txt",col_names = TRUE)
colnames(aol_data) <- colnames(aol_data) %>% fix_column_names
df <- aol_data %>%  
  group_by(anon_id) %>% 
  mutate(diff_time = c(0, diff(query_time)))

```
