---
title: "Assignment_3"
author: "Joseph Walker"
date: "3/19/2017"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

###Problem 1
The U.S. Government Department of Labor, Bureau of Labor Statistics (BLS) publishes a Local Area
Unemployent Report, overview available here:

* https://www.bls.gov/lau/lauov.htm

Data format description here:

* https://www.bls.gov/help/hlpforma.htm#LA


Assignment:
Tidy the data set provided and generate four separate ggplot line plots (including points) of the following:

1. Employment
2. Labor Force
3. Unemploment Rate
4. Unemployment



```{r sf_oak_metro data}
#load packages
library(tidyverse)
library(forcats)
library(lubridate)
library(pals)
library(Polychrome)
#read in data
df<- read_csv("sf_oak_metro.csv", col_names = T)


#06 Labor force,
#05 Employment,
#04 Unemployment, and
#03 Unemployment rate.

#tidy Data
sf_oak <- gather(df, Date, Value, -`Series ID`)

#uniform column names (lower case)
colnames(sf_oak) <- colnames(sf_oak) %>% tolower()

sf_oak$`series id` <- sf_oak$`series id` %>% 
                      fct_recode(unemployment_rate = "LAUMT064186000000003",
                                 unemployment = "LAUMT064186000000004",
                                 employment = "LAUMT064186000000005",
                                 labor_force = "LAUMT064186000000006")


sf_oak$date <- parse_date_time2(sf_oak$date, '%b! %Y!')
#sf_oak$value <- as.integer(sf_oak$value)
sf_oak$month <- month(sf_oak$date,label = TRUE)
sf_oak$year <- as.factor(year(sf_oak$date))

sf_oak %>%
  filter(`series id` == 'employment') %>%
  ggplot(aes(month, value, group = year, colour = year)) +
  geom_point() +
  geom_line() +
  ggtitle(label = 'Monthly Employment Statistics for the San Francisco-Oakland-Hayward Metropolitan Area', 
          subtitle = '1990-2016') +
  theme(plot.title = element_text(size = 10, face = 'bold'),
        plot.subtitle = element_text(size = 10))


sf_oak %>%
  filter(`series id` == 'labor_force') %>%
  ggplot(aes(month, value, group = year, colour = year)) +
  geom_point() +
  geom_line() +
  ggtitle(label = 'Monthly Labor Force Statistics for the San Francisco-Oakland-Hayward Metropolitan Area', 
          subtitle = '1990-2016') +
  theme(plot.title = element_text(size = 10, face = 'bold'),
        plot.subtitle = element_text(size = 10))

sf_oak %>%
  filter(`series id` == 'unemployment') %>%
  ggplot(aes(month, value, group = year, colour = year)) +
  geom_point() +
  geom_line() +
  ggtitle(label = 'Monthly Unemployment Statistics for the San Francisco-Oakland-Hayward Metropolitan Area', 
          subtitle = '1990-2016') +
  theme(plot.title = element_text(size = 10, face = 'bold'),
        plot.subtitle = element_text(size = 10))

sf_oak %>%
  filter(`series id` == 'unemployment_rate') %>%
  ggplot(aes(month, value, group = year, colour = year)) +
  geom_point() +
  geom_line() +
  ggtitle(label = 'Monthly Unemployment Rate Statistics for the San Francisco-Oakland-Hayward Metropolitan Area', 
          subtitle = '1990-2016') +
  theme(plot.title = element_text(size = 10, face = 'bold'),
        plot.subtitle = element_text(size = 10))

```

